### PR TITLE
Fix/mobile menu

### LINKED ISSUE #1556: Mobile UI issue
**Describe the bug**
When on mobile, if you tap the hamburger menu, you can't scroll, so depending on screen size and which submenus are expanded, you might not be able to access the whole menu.

**To Reproduce**
1. Go to https://explorer.hiro.so
2. Tap on the hamburger menu
3. Try to swipe down
4. If the whole menu fits, expand the network or rotate to landscape to see the problem.

**Expected behavior**
I should be able to scroll down to see the rest of the menu.

**Screenshots**
In this screenshot, I can't change the network to testnet because I can't scroll down.

IMG_7225

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.3.1
 - Browser: Safari or Chrome

### PR DESCRIPTION
**Pull request by BLuEScioN**
Fixes inability to scroll the mobile menu

Closes #1556

### CODE REVIEW

File: src/common/utils/utils.ts [hunk 1]
```diff
@@ -343,3 +343,18 @@ export function removeTrailingSlash(url?: string) {
   if (!url) return '';
   return url.replace(/\/$/, '');
 }
+
+export function promiseWrapper<T, Args extends any[]>(
```
Comment (He1DAr) [inline src/common/utils/utils.ts:347]: Can you explain the purpose of this function?

Comment (BLuEScioN) [reply src/common/utils/utils.ts:347]: I think this PR was accidentally branched from this [PR](https://github.com/hirosystems/explorer/pull/1687), so it has all those changes. I made a new PR that removed all those changes. The mobile menu PR is a 1 liner. The new PR is [here](https://github.com/hirosystems/explorer/compare/fix/mobile-menu2?expand=1).

But to ansewr the question, this is for my fix for the delete network bug. I saw that you had made addCustomNetwork return a promise, just so you could add a .then hook to it. Instead of muddying the implementation of addCustomNetwork I added this utility function that allows you to take a function, wrap it in a promise that resolves after the function is called, which allows us to add .then hooks to any function we want

**Review by He1DAr — APPROVED** [review]
