### PR TITLE
fix: upgrade to v2 addresses endpoint

### LINKED ISSUE #2555: asset transfer Tx does not show up in the recipient wallet Tx list
**Describe the bug**
When transferring sBTC to another wallet, the Tx shows up in the source wallet's Tx history but it does not show up in the destination address's Tx history.

Transaction ID 0xf8bd292ba1c89a6a04edf8645fc918e472edb060b01c19599df76bc91980ccba
Address SP1Y3FBARS8CVANS1GCYVN3B6NZFMA7H61Z6TP6RK
Block#  4247020
Time stamp 2025-10-17 21:07:45

**To Reproduce**
send sBTC to another wallet

**Expected behavior**
The Tx shows up in destination wallet's Tx history.

### PR DESCRIPTION
**Pull request by heidar-stacks**
## What type of PR is this? (check all applicable)
- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
upgrade to v2 addresses endpoint

## Issue ticket number and link
closes #2555

# Checklist:
- [x] I have performed a self-review of my code.
- [x] I have tested the change on desktop and mobile.
- [ ] I have added thorough tests where applicable.
- [ ] I've added analytics and error logging where applicable.

### CODE REVIEW

File: src/common/components/table/table-examples/AddressTxsTable.tsx [hunk 1]
```diff
@@ -245,7 +245,10 @@ export function AddressTxsTable({
     }
   );
 
-  const { total, results: txs = [] } = data || {};
+  const { total, results = [] } = data || {};
+  const txs = results
+    .map(item => item?.tx)
+    .filter((tx): tx is NonNullable<typeof tx> => tx != null);
```
Comment (nick-stacks) [inline src/common/components/table/table-examples/AddressTxsTable.tsx]: Why are we not just compressing it before we send it to the client?
