### PR TITLE
fix: rename "To" field and add "Tokens transferred" field to tx overview

### LINKED ISSUE #2578: sBTC recipient shown as the contract
**Describe the bug**

When sending sBTC the explorer shows the receipient as the sBTC contract.

**To Reproduce**
1. Send sBTC
2. Check on Explorer

**Expected behavior**

Show the actual recipient (maybe an issue with all FTs?)

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by heidar-stacks**
## What type of PR is this? (check all applicable)
- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
- rename "To" field to be more explicit
- add new field "Tokens transferred" that is renders all STX/FT/NFT transfers
caveats: 
- we'll skip rendering the new field if tx has more than 100 events (max page size for events)
 
## Issue ticket number and link
closes #2578

# Checklist:
- [x] I have performed a self-review of my code.
- [x] I have tested the change on desktop and mobile.
- [x] I have added thorough tests where applicable.
- [ ] I've added analytics and error logging where applicable.

### CODE REVIEW

File: src/app/txid/[txId]/redesign/tx-summary/getRecipientAddress.ts [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+  ContractCallTransaction,
+  MempoolContractCallTransaction,
+} from '@stacks/stacks-blockchain-api-types';
+
+export function getRecipientAddress(
+  tx: ContractCallTransaction | MempoolContractCallTransaction
+): string {
+  const contractId = tx.contract_call?.contract_id || '';
+
+  if ('block_height' in tx && tx.block_height !== undefined) {
```
Comment (nick-stacks) [inline src/app/txid/[txId]/redesign/tx-summary/getRecipientAddress.ts]: can we use the isconfirmed util func here please?

File: src/app/txid/[txId]/redesign/tx-summary/getRecipientAddress.ts [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+    const events = tx.events || [];
+
+    const transferEvent = events.find(
+      event =>
+        (event.event_type === 'fungible_token_asset' ||
+          event.event_type === 'non_fungible_token_asset') &&
+        event.asset.asset_event_type === 'transfer'
+    );
+
+    if (transferEvent && 'asset' in transferEvent) {
```
Comment (nick-stacks) [inline src/app/txid/[txId]/redesign/tx-summary/getRecipientAddress.ts]: What if there are multiple transfer events?

File: src/app/txid/[txId]/redesign/tx-summary/getRecipientAddress.ts [hunk 3]
```diff
@@ -0,0 +1,27 @@
+import {
+  ContractCallTransaction,
+  MempoolContractCallTransaction,
+} from '@stacks/stacks-blockchain-api-types';
+
+export function getRecipientAddress(
```
Comment (nick-stacks) [inline src/app/txid/[txId]/redesign/tx-summary/getRecipientAddress.ts]: I think this should live in transaction-utils.ts

File: src/app/txid/[txId]/redesign/tx-summary/__tests__/getRecipientAddress.test.ts [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+};
+
+describe('getRecipientAddress', () => {
+  it('returns contract ID when no transfer events', () => {
+    expect(getRecipientAddress(baseTx)).toBe(
+      'SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.sbtc-token'
+    );
+  });
+
+  it('returns recipient from FT transfer event', () => {
```
Comment (nick-stacks) [inline src/app/txid/[txId]/redesign/tx-summary/__tests__/getRecipientAddress.test.ts]: Can we add a test for multiple transfer events and multiple transfers that involve different asset types (ie different fts, or fts and nfts)?

**Review by nick-stacks — DISMISSED** [review]
