### PR TITLE
fix: mobile menu settings overlapping

### LINKED ISSUE #2236: [Mobile] sBTC link on Menu takes me to Testnet Explorer
https://github.com/user-attachments/assets/f25431d1-4979-446f-9bbc-d1fb6a9db8eb

### PR DESCRIPTION
**Pull request by He1DAr**
## What type of PR is this? (check all applicable)
- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
-Fix mobile menu settings overlapping

## Issue ticket number and link
closes #2236

# Checklist:
- [x] I have performed a self-review of my code.
- [x] I have tested the change on desktop and mobile.
- [ ] I have added thorough tests where applicable.
- [ ] I've added analytics and error logging where applicable.

### CODE REVIEW

File: src/app/_components/NewNavBar/MobileNavPage.tsx [hunk 1]
```diff
@@ -46,9 +46,10 @@ const MobileContentTop = ({
 
         <motion.div
           key="settings-menu"
-          initial={{ opacity: 0 }}
+          initial={{ opacity: 0, zIndex: -1, position: 'relative' }}
```
Comment (BLuEScioN) [inline src/app/_components/NewNavBar/MobileNavPage.tsx:49]: Is it possible to do this with display none and display block? Manipulating z-indices can get messy over time
